version: "3"
services:
  db:
    image: "postgres:10.6-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: corona-app
    volumes:
      - coronaapp:/var/lib/postgresql/data
volumes:
  coronaapp: