spring:
  datasource:
    url: jdbc:postgresql://localhost/corona-app
    username: root
    password: pw

  flyway:
    url: jdbc:postgresql://localhost/corona-app
    user: root
    password: pw

server:
  servlet:
    context-path: /api
